export const mockData = {
  form: { id: "5e5c85f", name: "FORM - Estou interessado" },
  fields: {
    subdomain: {
      id: "subdomain",
      type: "hidden",
      title: "Subdomínio",
      value: "worldcarfortaleza",
      raw_value: "worldcarfortaleza",
      required: "1",
    },
    contaId: {
      id: "contaId",
      type: "hidden",
      title: "Conta ID",
      value: 34853587,
      raw_value: "34853587",
      required: "1",
    },
    nome: {
      id: "nome",
      type: "text",
      title: "Nome",
      value: "João Silva",
      raw_value: "João Silva",
      required: "1",
    },
    telefone: {
      id: "telefone",
      type: "maskphone_with_ddd",
      title: "Telefone",
      value: "(11) 99999-9999",
      raw_value: "(11) 99999-9999",
      required: "1",
    },
    email: {
      id: "email",
      type: "email",
      title: "E-mail",
      value: "joao@example.com",
      raw_value: "joao@example.com",
      required: "1",
    },
    unidade: {
      id: "unidade",
      type: "select",
      title: "Unidade",
      value: "Fortaleza",
      raw_value: "Fortaleza",
      required: "0",
    },
    cursodeinteresse: {
      id: "cursodeinteresse",
      type: "select",
      title: "Curso de Interesse",
      value: "Programação",
      raw_value: "Programação",
      required: "0",
    },
    midia: {
      id: "midia",
      type: "hidden",
      title: "Mídia",
      value: "Facebook",
      raw_value: "Facebook",
      required: "0",
    },
    origem: {
      id: "origem",
      type: "hidden",
      title: "Origem",
      value: "Landing Page",
      raw_value: "Landing Page",
      required: "0",
    },
    profissao: {
      id: "profissao",
      type: "text",
      title: "Profissão",
      value: "Desenvolvedor",
      raw_value: "Desenvolvedor",
      required: "0",
    },
    utm_content: {
      id: "utm_content",
      type: "hidden",
      title: "UTM Content",
      value: "banner_principal",
      raw_value: "banner_principal",
      required: "0",
    },
    utm_medium: {
      id: "utm_medium",
      type: "hidden",
      title: "UTM Medium",
      value: "cpc",
      raw_value: "cpc",
      required: "0",
    },
    utm_campaign: {
      id: "utm_campaign",
      type: "hidden",
      title: "UTM Campaign",
      value: "curso_programacao_2025",
      raw_value: "curso_programacao_2025",
      required: "0",
    },
    utm_source: {
      id: "utm_source",
      type: "hidden",
      title: "UTM Source",
      value: "facebook",
      raw_value: "facebook",
      required: "0",
    },
    utm_term: {
      id: "utm_term",
      type: "hidden",
      title: "UTM Term",
      value: "curso+programacao",
      raw_value: "curso+programacao",
      required: "0",
    },
    utm_referrer: {
      id: "utm_referrer",
      type: "hidden",
      title: "UTM Referrer",
      value: "www.facebook.com",
      raw_value: "www.facebook.com",
      required: "0",
    },
    referrer: {
      id: "referrer",
      type: "hidden",
      title: "Referrer",
      value: "https://www.facebook.com",
      raw_value: "https://www.facebook.com",
      required: "0",
    },
    gclientid: {
      id: "gclientid",
      type: "hidden",
      title: "Google Client ID",
      value: "123456789.0987654321",
      raw_value: "123456789.0987654321",
      required: "0",
    },
    gclid: {
      id: "gclid",
      type: "hidden",
      title: "Google Click ID",
      value: "CjwKCAjw1234567890",
      raw_value: "CjwKCAjw1234567890",
      required: "0",
    },
    fbclid: {
      id: "fbclid",
      type: "hidden",
      title: "Facebook Click ID",
      value: "IwAR1234567890abcdef",
      raw_value: "IwAR1234567890abcdef",
      required: "0",
    },
    // Additional fields for info object
    cidade: {
      id: "cidade",
      type: "text",
      title: "Cidade",
      value: "Fortaleza",
      raw_value: "Fortaleza",
      required: "0",
    },
    estado: {
      id: "estado",
      type: "select",
      title: "Estado",
      value: "CE",
      raw_value: "CE",
      required: "0",
    },
    idade: {
      id: "idade",
      type: "number",
      title: "Idade",
      value: "28",
      raw_value: "28",
      required: "0",
    },
    genero: {
      id: "genero",
      type: "radio",
      title: "Gênero",
      value: "Masculino",
      raw_value: "Masculino",
      required: "0",
    },
    nivel_interesse: {
      id: "nivel_interesse",
      type: "select",
      title: "Nível de Interesse",
      value: "Alto",
      raw_value: "Alto",
      required: "0",
    },
    observacoes: {
      id: "observacoes",
      type: "textarea",
      title: "Observações",
      value: "Cliente demonstrou muito interesse no curso",
      raw_value: "Cliente demonstrou muito interesse no curso",
      required: "0",
    },
  },
  meta: {
    date: { title: "Data", value: "05/08/2025" },
    time: { title: "Horário", value: "17:39" },
    page_url: {
      title: "URL da página",
      value: "https://exemplo.com/cursos/programacao",
    },
  },
};
